import { Tool } from "@modelcontextprotocol/sdk/types.js";

export const tools: Tool[] = [
  // ── Health / Context ──
  { name: "gtm_get_client_context", description: "Health check and status overview. Returns GTM container path, workspace ID, GA4 property ID, and server version. Use this to verify connectivity.", inputSchema: { additionalProperties: false, type: "object", properties: {} } },
  // ── GTM Tools ──
  { name: "gtm_list_tags", description: "List all tags in the sandbox GTM workspace with name, type, consent status, and firing triggers.", inputSchema: { additionalProperties: false, type: "object", properties: {} } },
  { name: "gtm_get_tag", description: "Get full details of a single tag by ID from the sandbox workspace.", inputSchema: { additionalProperties: false, type: "object", properties: { tag_id: { type: "string", description: "The tag ID" } }, required: ["tag_id"] } },
  { name: "gtm_update_tag", description: "Update a tag in the sandbox workspace. Fetches current tag, merges updates, then saves. Safety: only operates on sandbox workspace.", inputSchema: { additionalProperties: false, type: "object", properties: { tag_id: { type: "string", description: "The tag ID" }, updates_json: { type: "string", description: "JSON object with fields to update (e.g. consentSettings, parameter)" } }, required: ["tag_id", "updates_json"] } },
  { name: "gtm_create_tag", description: "Create a new tag in the sandbox workspace. Safety: only operates on sandbox workspace.", inputSchema: { additionalProperties: false, type: "object", properties: { tag_json: { type: "string", description: "Full GTM tag JSON" } }, required: ["tag_json"] } },
  { name: "gtm_list_triggers", description: "List all triggers in the sandbox GTM workspace.", inputSchema: { additionalProperties: false, type: "object", properties: {} } },
  { name: "gtm_list_variables", description: "List all variables in the sandbox GTM workspace.", inputSchema: { additionalProperties: false, type: "object", properties: {} } },
  { name: "gtm_audit_consent", description: "Scan all tags in the sandbox workspace and report consent compliance. Returns tags with no consent, NOT_NEEDED tags, properly configured tags, and recommendations.", inputSchema: { additionalProperties: false, type: "object", properties: {} } },
  { name: "gtm_preview", description: "Generate a GTM Preview URL for the sandbox workspace.", inputSchema: { additionalProperties: false, type: "object", properties: {} } },
  { name: "gtm_create_version", description: "Create a version (snapshot) of the sandbox workspace. Does NOT publish.", inputSchema: { additionalProperties: false, type: "object", properties: { name: { type: "string", description: 'Version name (e.g., "Consent fixes v1")' }, notes: { type: "string", description: "Optional version notes" } }, required: ["name"] } },
  // ── GA4 Tools (prefixed with gtm_ to avoid collision with standalone mcp-ga4) ──
  { name: "gtm_ga4_run_report", description: "Query GA4 historical report for the property linked to this GTM container.", inputSchema: { additionalProperties: false, type: "object", properties: { dimensions: { type: "string", description: 'Comma-separated dimensions (e.g., "eventName,date")' }, metrics: { type: "string", description: 'Comma-separated metrics (e.g., "eventCount,activeUsers")' }, start_date: { type: "string", description: 'Start date (YYYY-MM-DD or "7daysAgo")' }, end_date: { type: "string", description: 'End date (YYYY-MM-DD or "today")' }, dimension_filter: { type: "string", description: 'Optional equality filter (e.g., "eventName==page_view")' }, limit: { type: "number", description: "Max rows (default 100)" } } } },
  { name: "gtm_ga4_realtime_report", description: "Query GA4 Realtime Report (last 30 minutes) for the property linked to this GTM container.", inputSchema: { additionalProperties: false, type: "object", properties: { dimensions: { type: "string", description: 'Comma-separated dimensions' }, metrics: { type: "string", description: 'Comma-separated metrics' }, dimension_filter: { type: "string", description: 'Optional equality filter' } } } },
  { name: "gtm_ga4_list_custom_dimensions", description: "List all registered custom dimensions for the GA4 property linked to this GTM container.", inputSchema: { additionalProperties: false, type: "object", properties: {} } },
  { name: "gtm_ga4_create_custom_dimension", description: "Register a new custom dimension in the GA4 property linked to this GTM container.", inputSchema: { additionalProperties: false, type: "object", properties: { parameter_name: { type: "string", description: 'Event parameter name (e.g., "form_type")' }, display_name: { type: "string", description: 'Human-readable name (e.g., "Form Type")' }, scope: { type: "string", description: '"EVENT" or "USER" (default: EVENT)' }, description: { type: "string", description: "Optional description" } }, required: ["parameter_name", "display_name"] } },
];
